version: "3.9"

services:
  eightysix:
    image: eightysix
    container_name: eightysix_dev
    profiles: ["dev"]
    build:
      context: ./
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules #empty mount to not overwrite node_modules
    environment:
      - NODE_ENV="development"

  nginx:
    image: nginx:latest
    container_name: eightysix_nginx
    profiles: ["prod"]
    volumes:
      - $PWD/dist:/usr/share/nginx/html
    restart: always
    network_mode: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.86.rule=Host(`86.agentzhao.me`)"
      - "traefik.http.routers.86.tls=true"
      - "traefik.http.routers.86.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.86.entrypoints=websecure"
      - "traefik.port=80"
